apiVersion: v1
kind: Service
metadata:
  name: aws-k8s-react-app-project

spec:
  selector:
    app: aws-k8s-react-app-project
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-k8s-react-app-project

spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-k8s-react-app-project
  template:
    metadata:
      labels:
        app: aws-k8s-react-app-project
    spec:
      containers:
        - name: aws-k8s-react-app-project
          image: clequinio/aws-k8s-react-app
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "64Mi"
              cpu: "500m"